import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { cookies } from "next/headers";

const manrope = Manrope({
	variable: "--font-manrope",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const store = await cookies();

	const data = store.get("interviewer-cookie")?.value;
	const parsedData = JSON.parse(decodeURIComponent(data || "{}"));

	return (
		<html lang="en">
			<head>
				<link
					href="https://cdn.writeroo.net/fa/css/all.min.css"
					rel="stylesheet"
					type="text/css"
				/>
			</head>
			<body className={`${manrope.className} antialiased`}>
				<Providers cloud={parsedData}>{children}</Providers>
			</body>
		</html>
	);
}
